# Adding basic authentication middleware, looks in secrets for authenticated users
http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:        
        usersFile: "/run/secrets/basic_auth_credentials"
        realm: "Traefik 3 Basic Auth"